name: imx8mm-evk
summary: NXP i.MX8M Mini EVK support package
description: |
 Support files for booting i.MX8M Mini EVK board
version: 20-1
type: gadget

base: core20

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

confinement: strict
grade: stable

parts:
    arm-trusted-firmware:
        plugin: nil
        source: https://source.codeaurora.org/external/imx/imx-atf.git
        source-type: git
        source-tag: rel_imx_5.4.70_2.3.0
        override-build: |
            platform="imx8mm"
            make \
                CROSS_COMPILE=aarch64-linux-gnu- \
                PLAT=${platform} \
                BUILD_BASE=${SNAPCRAFT_PART_BUILD}/build \
                bl31 \
                -j$(nproc)
            make \
                CROSS_COMPILE=aarch64-linux-gnu- \
                PLAT=${platform} \
                BUILD_BASE=${SNAPCRAFT_PART_BUILD}/build-optee \
                SPD=opteed \
                bl31 \
                -j$(nproc)
            cp ${SNAPCRAFT_PART_BUILD}/build/${platform}/release/bl31.bin \
               ${SNAPCRAFT_PART_INSTALL}/bl31-${platform}.bin
            cp ${SNAPCRAFT_PART_BUILD}/build-optee/${platform}/release/bl31.bin \
               ${SNAPCRAFT_PART_INSTALL}/bl31-${platform}.bin-optee
        prime:
            - -*

    optee-fde:
        plugin: dump
        source: git+ssh://git.launchpad.net/~ondrak/+git/optee-uc-fde
        source-type: git
        organize:
            '*': optee-fde/
        prime:
            - -*

build-packages:
    - bison
    - build-essential
    - device-tree-compiler
    - flex
    - gcc-aarch64-linux-gnu
    - libxml2-dev
    - libssl-dev
    - python3
    - python3-crypto
    - python3-pyelftools
    - python3-pycryptodome
    - wget
    - zlib1g-dev
